pipelines:
  default:
    - step:
        services:
          - docker
        script:
          - export IMAGE_NAME=eu.gcr.io/the-dots/infrastructure-nginx:$BITBUCKET_BUILD_NUMBER
          - docker build -t $IMAGE_NAME .
          - echo $GCR_KEY | base64 -d | docker login -u _json_key --password-stdin https://eu.gcr.io
          - docker push $IMAGE_NAME
